
#line 2 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
typedef uint64_t flex_uint64_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern yy_size_t yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	yy_size_t yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static yy_size_t yy_n_chars;		/* number of characters read into yy_ch_buf */
yy_size_t yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, yy_size_t len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (yy_size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 32
#define YY_END_OF_BUFFER 33
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[146] =
    {   0,
        0,    0,   33,   31,    1,   18,   31,   31,   19,   31,
       31,   31,   29,   29,   15,   16,   31,   31,   31,   31,
       31,   31,   31,   31,   31,   31,   31,   31,   31,   31,
       31,   24,   31,   24,   24,   31,   24,   31,   31,   20,
       31,   31,    1,   17,   31,   31,   31,   31,   29,   29,
       31,    3,   31,   31,   31,   29,   28,   31,   29,   13,
       14,   31,   31,   31,   31,   31,   31,   31,   31,   31,
       31,   31,   31,   31,   31,    2,   31,   31,    0,   30,
       31,   31,   31,   31,   24,   31,   31,   31,   31,   31,
       21,    8,   12,    6,    4,   31,    0,   31,    5,    7,

       26,   31,   31,   31,   22,   22,   31,   31,   31,   31,
        2,   31,   31,   31,   31,   31,   31,   31,   30,   11,
       23,   23,   31,   31,    0,   25,   31,   10,    9,   31,
       31,   31,   31,    2,   25,   27,   31,   31,   31,   31,
       31,   31,   31,   31,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    4,    1,    5,    1,    6,    7,    8,    1,
        1,    9,   10,    1,   11,    1,   12,   13,   14,   14,
       14,   14,   14,   14,   14,   14,   14,    1,    1,   15,
        1,   16,    1,   17,   18,   19,   20,   21,   22,   23,
       24,   25,   18,   18,   18,   18,   26,   27,   18,   28,
       18,   29,   30,   18,   18,   31,   18,   18,   18,   18,
       32,    1,   33,   34,   35,    1,   36,   37,   38,   39,

       40,   18,   41,   42,   43,   18,   18,   44,   45,   46,
       47,   48,   18,   49,   50,   51,   52,   53,   18,   54,
       18,   55,    1,   56,    1,    1,    1,   57,   18,    1,
        1,    1,    1,    1,    1,    1,   18,    1,    1,    1,
       18,    1,    1,    1,   18,    1,   18,    1,    1,    1,
        1,    1,   58,   18,    1,   18,    1,    1,    1,    1,
       18,    1,    1,    1,    1,    1,    1,    1,   18,    1,
        1,    1,   18,    1,    1,   59,   18,    1,   18,    1,
        1,    1,    1,    1,    1,   18,    1,   18,    1,    1,
        1,    1,    1,   60,   18,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,   61,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[62] =
    {   0,
        1,    2,    3,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1
    } ;

static const flex_int16_t yy_base[152] =
    {   0,
        0,    0,  245,    0,   60,  240,  225,  224,  223,   53,
       57,  222,   66,  120,  217,  215,  181,  183,   29,  189,
      182,   33,  183,  190,  182,  172,  187,  179,  181,   70,
      209,    0,   35,  165,  178,  171,   41,  172,  159,    0,
      151,    0,   80,    0,  193,  192,  191,  190,  235,  289,
       85,    0,  189,   71,   91,    0,    0,  147,  343,  192,
      191,  404,  465,  154,  161,  153,  142,  143,  140,  136,
      133,  124,  138,  133,  127,  129,  125,   84,  140,   89,
      156,  133,  117,  119,    0,  128,  126,  120,  113,  117,
        0,    0,    0,    0,    0,   87,  149,  148,   95,    0,

       95,  100,  141,  140,    0,  535,  111,  114,  102,  104,
        0,  100,   96,  109,   99,   96,  106,   94,  106,    0,
        0,   98,   86,   85,  124,    0,   97,    0,    0,   89,
       95,   94,   78,   77,  535,   99,   79,   80,   74,   69,
       83,   82,   66,   53,  535,   99,   91,  526,  528,  530,
      532
    } ;

static const flex_int16_t yy_def[152] =
    {   0,
      145,    1,  145,  146,  145,  146,  146,  146,  146,  146,
      146,  146,  146,  146,  146,  146,  147,  146,  146,  146,
      146,  146,  146,  146,  146,  146,  146,  146,  146,  148,
      146,  146,  146,  146,  146,  146,  146,  146,  146,  146,
      146,  146,  145,  146,  146,  146,  146,  146,  146,  146,
      149,  146,  146,  146,  146,  146,  146,  146,  146,  146,
      146,  147,  146,  146,  146,  146,  146,  146,  146,  146,
      146,  146,  146,  146,  146,  146,  146,  148,  150,  148,
      146,  146,  146,  146,  146,  146,  146,  146,  146,  146,
      146,  146,  146,  146,  146,  149,  151,  146,  149,  146,

      146,  146,  146,  146,  146,  145,  146,  146,  146,  146,
      146,  146,  146,  146,  146,  146,  146,  146,  150,  146,
      146,  146,  146,  146,  145,  146,  146,  146,  146,  146,
      146,  146,  146,  146,  145,  146,  146,  146,  146,  146,
      146,  146,  146,  146,    0,  145,  145,  145,  145,  145,
      145
    } ;

static const flex_int16_t yy_nxt[597] =
    {   0,
        4,    5,    5,    4,    6,    7,    8,    4,    9,   10,
       11,   12,   13,   14,   15,   16,   17,    4,   18,   19,
       20,   21,   22,   23,   24,   25,   26,   27,    4,   28,
       29,   30,    4,   31,    4,    4,    4,   32,   33,   34,
        4,   35,   36,    4,   37,    4,    4,    4,   38,   39,
        4,    4,    4,    4,    4,   40,    4,    4,    4,   41,
        4,   43,   43,   48,   65,   49,   50,   51,   69,   49,
       50,   79,   52,   54,   82,   66,   70,   83,   55,   55,
       85,   43,   43,  101,  101,   79,   97,   87,   97,   56,
       79,   62,   88,   56,   57,   98,   97,   98,   54,   42,

       99,  111,   80,   55,   55,   98,   56,  101,  101,  136,
      136,  136,  136,   56,   57,  111,   80,  144,  143,   57,
      142,   80,  141,  111,  140,  111,   58,   54,  139,  138,
      111,  137,   59,   59,  135,  121,  121,  121,  119,   57,
      111,  134,  111,   56,  133,  132,  131,   56,   57,  111,
      111,   58,  130,  111,  111,  129,  128,  127,  126,  125,
       56,  121,  124,  123,  121,  121,  121,   56,   57,  122,
      121,  120,  119,  111,  118,  117,  116,  115,  111,  114,
       58,   42,  113,  112,   42,   42,   42,   42,   42,   42,
       42,   42,   42,  111,  110,   42,   42,   42,  109,  108,

      107,  104,  103,  102,  100,   95,   94,   93,   92,   91,
       90,   89,   42,   42,   42,   63,   86,   85,   84,   81,
       77,   76,   75,   74,   73,   72,   71,   68,   67,   64,
       61,   60,   53,   47,   46,   45,   42,   42,   42,   42,
       42,   42,   54,   44,  145,  145,  145,   55,   55,  145,
      145,  145,  145,  145,  145,  145,  145,  145,   56,  145,
      145,  145,   56,   57,  145,  145,  145,  145,  145,  145,
      145,  145,  145,  145,  145,   56,  145,  145,  145,  145,
      145,  145,   56,   57,  145,  145,  145,  145,  145,  145,
      145,  145,  145,  145,  145,   58,   54,  145,  145,  145,

      145,   59,   59,  145,  145,  145,  145,  145,  145,  145,
      145,  145,   56,  145,  145,  145,   56,   57,  145,  145,
      145,  145,  145,  145,  145,  145,  145,  145,  145,   56,
      145,  145,  145,  145,  145,  145,   56,   57,  145,  145,
      145,  145,  145,  145,  145,  145,  145,  145,  145,   58,
       54,  145,  145,  145,  145,   59,   59,  145,  145,  145,
      145,  145,  145,  145,  145,  145,   56,  145,  145,  145,
       56,   57,  145,  145,  145,  145,  145,  145,  145,  145,
      145,  145,  145,   56,  145,  145,  145,  145,  145,  145,
       56,   57,  145,  145,  145,  145,  145,  145,  145,  145,

      145,  145,  145,   58,   42,  145,  145,   42,   42,   42,
       42,   42,   42,   42,   42,   42,  145,  145,   42,   42,
       42,  145,  145,  145,  145,  145,  145,  145,  145,  145,
      145,  145,  145,  145,  145,   42,   42,   42,   63,  145,
      145,  145,  145,  145,  145,  145,  145,  145,  145,  145,
      145,  145,  145,  145,  145,  145,  145,  145,  145,   42,
       42,   42,   42,   42,   42,  105,  106,  106,  105,  105,
      105,  105,  105,  105,  105,  105,  105,  145,  145,  105,
      105,  145,  145,  145,  145,  145,  145,  145,  145,  145,
      145,  145,  145,  145,  145,  145,  105,  105,  105,  105,

      145,  145,  145,  145,  145,  145,  145,  145,  145,  145,
      145,  145,  145,  145,  145,  145,  145,  145,  145,  145,
      105,  105,  105,  105,  105,  105,   78,   78,   96,   96,
       79,   79,   97,   97,    3,  145,  145,  145,  145,  145,
      145,  145,  145,  145,  145,  145,  145,  145,  145,  145,
      145,  145,  145,  145,  145,  145,  145,  145,  145,  145,
      145,  145,  145,  145,  145,  145,  145,  145,  145,  145,
      145,  145,  145,  145,  145,  145,  145,  145,  145,  145,
      145,  145,  145,  145,  145,  145,  145,  145,  145,  145,
      145,  145,  145,  145,  145,  145

    } ;

static const flex_int16_t yy_chk[597] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    5,    5,   10,   19,   10,   10,   11,   22,   11,
       11,   30,   11,   13,   33,   19,   22,   33,   13,   13,
       37,   43,   43,   54,   54,   78,   51,   37,   96,   13,
       80,  147,   37,   13,   13,   51,   99,   96,   55,  146,

       51,  144,   30,   55,   55,   99,   13,  101,  101,  127,
      127,  136,  136,   13,   13,  143,   78,  142,  141,   55,
      140,   80,  139,  138,  137,  134,   13,   14,  133,  132,
      131,  130,   14,   14,  125,  124,  123,  122,  119,   55,
      118,  117,  116,   14,  115,  114,  113,   14,   14,  112,
      110,   55,  109,  108,  107,  104,  103,  102,   98,   97,
       14,   90,   89,   88,   87,   86,   84,   14,   14,   83,
       82,   81,   79,   77,   76,   75,   74,   73,   72,   71,
       14,   17,   70,   69,   17,   17,   17,   17,   17,   17,
       17,   17,   17,   68,   67,   17,   17,   17,   66,   65,

       64,   61,   60,   58,   53,   48,   47,   46,   45,   41,
       39,   38,   17,   17,   17,   17,   36,   35,   34,   31,
       29,   28,   27,   26,   25,   24,   23,   21,   20,   18,
       16,   15,   12,    9,    8,    7,   17,   17,   17,   17,
       17,   17,   49,    6,    3,    0,    0,   49,   49,    0,
        0,    0,    0,    0,    0,    0,    0,    0,   49,    0,
        0,    0,   49,   49,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,   49,    0,    0,    0,    0,
        0,    0,   49,   49,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,   49,   50,    0,    0,    0,

        0,   50,   50,    0,    0,    0,    0,    0,    0,    0,
        0,    0,   50,    0,    0,    0,   50,   50,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,   50,
        0,    0,    0,    0,    0,    0,   50,   50,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,   50,
       59,    0,    0,    0,    0,   59,   59,    0,    0,    0,
        0,    0,    0,    0,    0,    0,   59,    0,    0,    0,
       59,   59,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,   59,    0,    0,    0,    0,    0,    0,
       59,   59,    0,    0,    0,    0,    0,    0,    0,    0,

        0,    0,    0,   59,   62,    0,    0,   62,   62,   62,
       62,   62,   62,   62,   62,   62,    0,    0,   62,   62,
       62,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,   62,   62,   62,   62,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,   62,
       62,   62,   62,   62,   62,   63,   63,   63,   63,   63,
       63,   63,   63,   63,   63,   63,   63,    0,    0,   63,
       63,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,   63,   63,   63,   63,

        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
       63,   63,   63,   63,   63,   63,  148,  148,  149,  149,
      150,  150,  151,  151,  145,  145,  145,  145,  145,  145,
      145,  145,  145,  145,  145,  145,  145,  145,  145,  145,
      145,  145,  145,  145,  145,  145,  145,  145,  145,  145,
      145,  145,  145,  145,  145,  145,  145,  145,  145,  145,
      145,  145,  145,  145,  145,  145,  145,  145,  145,  145,
      145,  145,  145,  145,  145,  145,  145,  145,  145,  145,
      145,  145,  145,  145,  145,  145

    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "scanner.l"
/*
-----------------------------------------------------------------------
TABLA DE EQUIVALENCIAS LÉXICAS (Átomos)
-----------------------------------------------------------------------
Asigna un símbolo terminal (átomo) a cada tipo de token.
Útil para alimentar el análisis sintáctico posteriormente.
*/
/*
 * scanner.l – Analizador Léxico y Sintáctico Descendente Recursivo
 * 
 * Este archivo combina:
 * 1) El analizador léxico (Flex) para tokenizar el lenguaje definido en el Anexo A.
 * 2) Un parser LL(1) embebido en C que consume los átomos generados.
 *
 * El analizador léxico identifica:
 * - Palabras reservadas (clase 0) y genera sus átomos.
 * - Símbolos especiales (clase 1).
 * - Identificadores (clase 2).
 * - Operadores aritméticos (clase 3).
 * - Operadores relacionales (clase 4).
 * - Operadores de asignación (clase 5).
 * - Literales (cadenas, enteros, reales).
 * - Comentarios y errores léxicos.
 *
 * El parser embebido recorre la cadena de átomos y verifica la sintaxis según la gramática LL(1).
 * Incluye funciones para cada no-terminal y muestra mensajes de depuración (DEBUG).
 */
/* === INCLUSIÓN DE CABECERAS Y DEFINICIONES GLOBALES === */
#line 33 "scanner.l"
#define YY_NO_MAIN 1
/*
Descripción del Programa

El presente programa es un Analizador Léxico desarrollado utilizando la herramienta Flex (Fast Lexical Analyzer Generator). El objetivo principal del analizador léxico es identificar y clasificar correctamente los componentes básicos de un lenguaje específico a partir de un código fuente.

El analizador reconoce diferentes categorías de tokens como palabras reservadas, identificadores, símbolos especiales, operadores aritméticos, relacionales y de asignación, así como constantes numéricas (enteras y reales) y cadenas literales. Además, ignora comentarios y maneja errores léxicos, mostrando información útil sobre estos últimos en la salida estándar.

El programa estructura la información obtenida en tres tablas:
•	Tabla de Tokens: Contiene los tokens reconocidos con su clasificación y posición respectiva.
•	Tabla de Símbolos: Almacena los identificadores encontrados en el código.
•	Tabla de Literales: Guarda cadenas y constantes numéricas detectadas.

Cada una de estas tablas se exporta en archivos separados (tokens.txt, simbolos.txt y literales.txt) para facilitar posteriores etapas de análisis sintáctico y semántico.

⸻

Autores del Programa:
•	Yaretzi Calzontzi Hernández
•	Emilio Sebastián Contreras Colmenero

Fecha de elaboracion: 15/03/25
-----------------------------------------------------------------------
INSTRUCCIONES DE CABECERA
-----------------------------------------------------------------------
Este bloque se utiliza para incluir bibliotecas de C y declaraciones 
globales. También definimos estructuras para la tabla de símbolos, 
tabla de literales y la tabla de tokens. 
*/

#include <stdio.h>
#include <string.h>
#include <stdlib.h>

#define MAX_TOKENS 300

/* === DEFINICIÓN DE ESTRUCTURAS PARA TABLAS DE SÍMBOLOS Y LITERALES === */

typedef struct {
int pos;
char nombre[50];
int tipo; 
} Simbolo;

/* === MAPEADO DE CLASES Y POSICIONES A ÁTOMOS LÉXICOS === */

const char* obtener_atomo(int clase, int posicion) {
switch (clase) {
    case 0: {
        switch (posicion) {
            case 0: return "b";  // Bool
            case 1: return "c";  // Cade
            case 2: return "t";  // Continuar
            case 3: return "d";  // Devo
            case 4: return "n";  // Ent
            case 5: return "q";  // Fals
            case 6: return "f";  // Flota
            case 7: return "g";  // Global
            case 8: return "h";  // Haz
            case 9: return "w";  // Mientras
            case 10: return "u"; // Nulo
            case 11: return "o"; // Para
            case 12: return "p"; // Parar
            case 13: return "i"; // Si
            case 14: return "l"; // Sino
            case 15: return "m"; // Ver
            default: return "?";
        }
    }
 case 1: {
    switch (posicion) {
        case 0: return "(";  // <
        case 1: return ")";  // >
        case 2: return "[";  // <<
        case 3: return "]";  // >>
        case 4: return "{";  // #
        case 5: return "}";  // #!
        case 6: return ";";  // *
        case 7: return ",";  // |
        case 8: return ".";  // °
        default: return "?";
    }
}
    case 2: return "a"; // Identificador
    case 3: {
        switch (posicion) {
            case 0: return "+"; // sum
            case 1: return "-"; // rest
            case 2: return "*"; // mult
            case 3: return "/"; // div
            case 4: return "%"; // mod
            case 5: return "z"; // inc
            case 6: return "j"; // dec
            case 7: return "k"; // exp
            case 8: return "~"; // dive (changed from '&' to '~')
            default: return "?";
        }
    }
    case 4: {
        switch (posicion) {
            case 0: return ">"; // h
            case 1: return "<"; // m
            case 2: return "¡"; // e
            case 3: return "!"; // c
            case 4: return "x"; // he
            case 5: return "y"; // me
            default: return "?";
        }
    }
    case 5: {
        switch (posicion) {
            case 0: return "=";   // ->
            case 1: return "#";   // +->
            case 2: return "ñ";   // -->
            case 3: return "$";   // *->
            case 4: return "v";   // /->
            case 5: return "?";   // %->
            case 6: return ":";   // >>->
            case 7: return "\"";  // <<->
            case 8: return "^";   // ^->
            case 9: return "&";   // &->
            default: return "?";
        }
    }
    case 6: return "s"; // Cadena
    case 7: return "e"; // Entero
    case 8: return "r"; // Real
    case 9: return "!"; // Error léxico
    default: return "?";
}
}
/* === DEFINICIÓN DE ESTRUCTURAS PARA TABLAS DE SÍMBOLOS Y LITERALES === */
/* Tablas separadas para literales: cadenas, reales y enteros */
typedef struct {
int pos;
char dato[100];
} CadenaLiteral;

typedef struct {
int pos;
double valor;
} RealLiteral;

typedef struct {
int pos;
long valor;
} EnteroLiteral;

/* Estructura para la tabla de tokens.
Cada token tiene:
- clase: el código de la clase (0=reservada, 1=símbolo, 2=ident, etc.)
- posicion: el índice dentro de su tabla (o -1 si no aplica) */
typedef struct {
int clase;      
int posicion;   
} TokenInfo;

/* Declaración de tablas globales */
Simbolo tabla_simbolos[MAX_TOKENS];
int simbolos_count = 0;

CadenaLiteral cadena_literales[MAX_TOKENS];
int cadena_literales_count = 0;

RealLiteral real_literales[MAX_TOKENS];
int real_literales_count = 0;

EnteroLiteral entero_literales[MAX_TOKENS];
int entero_literales_count = 0;

TokenInfo tabla_tokens[MAX_TOKENS];
int token_count = 0;

/* Declaración de los archivos de salida */
FILE *archivo_tokens = NULL;
FILE *archivo_simbolos = NULL;
FILE *archivo_literales = NULL;
FILE *archivo_cadenas = NULL;
FILE *archivo_enteros = NULL;
FILE *archivo_reales = NULL;
FILE *archivo_errores = NULL;

/* 
Tablas predefinidas con las palabras reservadas, símbolos especiales,
operadores aritméticos, operadores relacionales y operadores de asignación.
Cada una tiene una posición fija en dichas tablas.
*/

/* Palabras reservadas (clase 0) */
const char *palabras_reservadas[] = {
"Bool", "Cade", "Continuar", "Devo", "Ent", "Fals", "Flota", "Global",
"Haz", "Mientras", "Nulo", "Para", "Parar", "Si", "Sino", "Ver"
};
const int total_palabras_reservadas = 16;

/* Símbolos especiales (clase 1) */
const char *simbolos_especiales[] = {
"<", ">", "<<", ">>", "#", "#!", "*", "|", "°"
};
const int total_simbolos_especiales = 9;

/* Operadores aritméticos (clase 3) */
const char *operadores_aritmeticos[] = {
"sum", "rest", "mult", "div", "mod", "inc", "dec", "exp", "dive"
};
const int total_operadores_aritmeticos = 9;

/* Operadores relacionales (clase 4) */
const char *operadores_relacionales[] = {
"h", "m", "e", "c", "he", "me"
};
const int total_operadores_relacionales = 6;

/* Operadores de asignación (clase 5) */
const char *operadores_asignacion[] = {
"->", "+->", "-->", "*->", "/->", "%->", ">>->", "<<->", "^->", "&->"
};
const int total_operadores_asignacion = 10;

/* 
-----------------------------------------------------------------------
DECLARACIÓN DE FUNCIONES
-----------------------------------------------------------------------
Funciones para buscar y asignar posiciones, así como para imprimir
las tablas resultantes.
*/

/* 
buscar_posicion:
Busca el valor 'valor' en la tabla[] de cadenas, devolviendo el índice
si lo encuentra, o -1 en caso contrario.
*/
int buscar_posicion(const char *valor, const char *tabla[], int total) {
    for (int i = 0; i < total; i++) {
        char limpio[50];
        strcpy(limpio, valor);
        limpio[strcspn(limpio, "\n")] = 0;
        if (strcmp(tabla[i], limpio) == 0) {
            return i;
        }
    }
    return -1;
}

/* === FUNCIONES AUXILIARES: GESTIÓN DE TABLAS DE SÍMBOLOS Y LITERALES === */

int obtener_posicion_simbolo(const char* nombre) {
for (int i = 0; i < simbolos_count; i++) {
    if (strcmp(tabla_simbolos[i].nombre, nombre) == 0) {
        return i; 
    }
}
if (simbolos_count < MAX_TOKENS) {
    tabla_simbolos[simbolos_count].pos = simbolos_count;
    strcpy(tabla_simbolos[simbolos_count].nombre, nombre);
    tabla_simbolos[simbolos_count].tipo = -1;
    return simbolos_count++;
}
return -1; 
}

int obtener_posicion_literal_cadena(const char* dato) {
for (int i = 0; i < cadena_literales_count; i++) {
    if (strcmp(cadena_literales[i].dato, dato) == 0) {
        return i;
    }
}
if (cadena_literales_count < MAX_TOKENS) {
    cadena_literales[cadena_literales_count].pos = cadena_literales_count;
    strcpy(cadena_literales[cadena_literales_count].dato, dato);
    return cadena_literales_count++;
}
return -1;
}

int obtener_posicion_literal_real(const char* dato) {
double valor = atof(dato);
for (int i = 0; i < real_literales_count; i++) {
    if (real_literales[i].valor == valor) {
        return i;
    }
}
if (real_literales_count < MAX_TOKENS) {
    real_literales[real_literales_count].pos = real_literales_count;
    real_literales[real_literales_count].valor = valor;
    return real_literales_count++;
}
return -1;
}

int obtener_posicion_literal_entero(const char* dato) {
long valor = strtol(dato, NULL, 10);
for (int i = 0; i < entero_literales_count; i++) {
    if (entero_literales[i].valor == valor) {
        return i;
    }
}
if (entero_literales_count < MAX_TOKENS) {
    entero_literales[entero_literales_count].pos = entero_literales_count;
    entero_literales[entero_literales_count].valor = valor;
    return entero_literales_count++;
}
return -1;
}

/* === AGREGAR TOKENS A LA TABLA Y EMITIR ÁTOMOS === */

void agregar_token(const char *valor, int clase, int posicion) {
    int pos = -1;
    if (posicion != -1) {
        pos = posicion;
    } else {
        switch (clase) {
            case 1:
                pos = buscar_posicion(valor, simbolos_especiales, total_simbolos_especiales);
                break;
            case 3:
                pos = buscar_posicion(valor, operadores_aritmeticos, total_operadores_aritmeticos);
                break;
            case 4:
                pos = buscar_posicion(valor, operadores_relacionales, total_operadores_relacionales);
                break;
            case 5:
                pos = buscar_posicion(valor, operadores_asignacion, total_operadores_asignacion);
                break;
            case 2:
                pos = obtener_posicion_simbolo(valor);
                break;
            case 6:
                pos = obtener_posicion_literal_cadena(valor);
                break;
            case 7:
                pos = obtener_posicion_literal_entero(valor);
                break;
            case 8:
                pos = obtener_posicion_literal_real(valor);
                break;
            case 9:
                pos = -1;
                break;
        }
    }

    if (clase != 9 && pos == -1) {
        return;
    }

    if (token_count < MAX_TOKENS) {
        tabla_tokens[token_count].clase = clase;
        tabla_tokens[token_count].posicion = pos;
        token_count++;

        const char* atomo = obtener_atomo(clase, pos);
        printf("Átomo: %s\n", atomo);

        FILE* archivo_atomos = fopen("atomos.txt", "a");
        if (archivo_atomos) {
            fprintf(archivo_atomos, "%s\n", atomo);
            fclose(archivo_atomos);
        }
    }
}

/* 
-----------------------------------------------------------------------
FUNCIONES PARA IMPRIMIR LAS TABLAS
-----------------------------------------------------------------------
Cada función escribe el resultado en el archivo *fp correspondiente.
*/

/* === FUNCIONES PARA IMPRIMIR TABLAS DE RESULTADOS EN ARCHIVOS === */

void imprimir_tabla_tokens(FILE *fp) {
fprintf(fp, "\n===== TABLA DE TOKENS =====\n");
fprintf(fp, "| %-5s | %-10s |\n", "Clase", "Posición");
fprintf(fp, "|------------------|\n");
for (int i = 0; i < token_count; i++) {
    fprintf(fp, "| %-5d | %-10d |\n",
            tabla_tokens[i].clase,
            tabla_tokens[i].posicion);
}
fprintf(fp, "==========================\n");
}
/* imprimir_tabla_simbolos:
Muestra la tabla de identificadores con pos, nombre y tipo. */

void imprimir_tabla_simbolos(FILE *fp) {
fprintf(fp, "\n===== TABLA DE SÍMBOLOS (IDENT) =====\n");
fprintf(fp, "| %-5s | %-15s | %-5s |\n", "Pos", "Nombre", "Tipo");
fprintf(fp, "|--------------------------------|\n");
for (int i = 0; i < simbolos_count; i++) {
    fprintf(fp, "| %-5d | %-15s | %-5d |\n",
        tabla_simbolos[i].pos,
        tabla_simbolos[i].nombre,
        tabla_simbolos[i].tipo);
}
fprintf(fp, "================================\n");
}

/* imprimir_tabla_literales:
Por compatibilidad, imprime todas las tablas de literales juntas (opcional). */
void imprimir_tabla_literales(FILE *fp) {
fprintf(fp, "\n===== TABLA DE LITERALES (Cadenas) =====\n");
fprintf(fp, "| %-5s | %-15s |\n", "Pos", "Valor");
fprintf(fp, "|-----------------------|\n");
for (int i = 0; i < cadena_literales_count; i++) {
    fprintf(fp, "| %-5d | %-15s |\n",
        cadena_literales[i].pos,
        cadena_literales[i].dato);
}
fprintf(fp, "=======================\n");
fprintf(fp, "\n===== TABLA DE LITERALES (Enteros) =====\n");
fprintf(fp, "| %-5s | %-15s |\n", "Pos", "Valor");
fprintf(fp, "|-----------------------|\n");
for (int i = 0; i < entero_literales_count; i++) {
    fprintf(fp, "| %-5d | %-15ld |\n",
        entero_literales[i].pos,
        entero_literales[i].valor);
}
fprintf(fp, "=======================\n");
fprintf(fp, "\n===== TABLA DE LITERALES (Reales) =====\n");
fprintf(fp, "| %-5s | %-15s |\n", "Pos", "Valor");
fprintf(fp, "|-----------------------|\n");
for (int i = 0; i < real_literales_count; i++) {
    fprintf(fp, "| %-5d | %-15g |\n",
        real_literales[i].pos,
        real_literales[i].valor);
}
fprintf(fp, "=======================\n");
}

void imprimir_tabla_cadenas(FILE *fp) {
fprintf(fp, "\n===== TABLA DE CADENAS =====\n");
fprintf(fp, "| %-5s | %-15s |\n", "Pos", "Valor");
fprintf(fp, "|-----------------------|\n");
for (int i = 0; i < cadena_literales_count; i++) {
    fprintf(fp, "| %-5d | %-15s |\n",
        cadena_literales[i].pos,
        cadena_literales[i].dato);
}
fprintf(fp, "=======================\n");
}

void imprimir_tabla_enteros(FILE *fp) {
fprintf(fp, "\n===== TABLA DE ENTEROS =====\n");
fprintf(fp, "| %-5s | %-15s |\n", "Pos", "Valor");
fprintf(fp, "|-----------------------|\n");
for (int i = 0; i < entero_literales_count; i++) {
    fprintf(fp, "| %-5d | %-15ld |\n",
        entero_literales[i].pos,
        entero_literales[i].valor);
}
fprintf(fp, "=======================\n");
}

void imprimir_tabla_reales(FILE *fp) {
fprintf(fp, "\n===== TABLA DE REALES =====\n");
fprintf(fp, "| %-5s | %-15s |\n", "Pos", "Valor");
fprintf(fp, "|-----------------------|\n");
for (int i = 0; i < real_literales_count; i++) {
    fprintf(fp, "| %-5d | %-15g |\n",
        real_literales[i].pos,
        real_literales[i].valor);
}
fprintf(fp, "=======================\n");
}
#line 1119 "lex.yy.c"
/* === REGLAS DE FLEX: DE DEFINICIONES LÉXICAS A TOKENS === */
#line 1121 "lex.yy.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			yy_size_t yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		yy_size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 503 "scanner.l"




#line 1343 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 146 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 535 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
/* rule 1 can match eol */
YY_RULE_SETUP
#line 507 "scanner.l"
{  }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 511 "scanner.l"
{
    int pos = buscar_posicion(yytext, palabras_reservadas, total_palabras_reservadas);
    agregar_token(yytext, 0, pos);
    printf("[CLASE 0 - Pal.Res]: %s (pos: %d)\n", yytext, pos);
}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 519 "scanner.l"
{ agregar_token(yytext, 5, 0); printf("[CLASE 5 - Op.Asig]: %s\n", yytext); }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 520 "scanner.l"
{ agregar_token(yytext, 5, 1); printf("[CLASE 5 - Op.Asig]: %s\n", yytext); }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 521 "scanner.l"
{ agregar_token(yytext, 5, 2); printf("[CLASE 5 - Op.Asig]: %s\n", yytext); }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 522 "scanner.l"
{ agregar_token(yytext, 5, 3); printf("[CLASE 5 - Op.Asig]: %s\n", yytext); }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 523 "scanner.l"
{ agregar_token(yytext, 5, 4); printf("[CLASE 5 - Op.Asig]: %s\n", yytext); }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 524 "scanner.l"
{ agregar_token(yytext, 5, 5); printf("[CLASE 5 - Op.Asig]: %s\n", yytext); }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 525 "scanner.l"
{ agregar_token(yytext, 5, 6); printf("[CLASE 5 - Op.Asig]: %s\n", yytext); }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 526 "scanner.l"
{ agregar_token(yytext, 5, 7); printf("[CLASE 5 - Op.Asig]: %s\n", yytext); }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 527 "scanner.l"
{ agregar_token(yytext, 5, 8); printf("[CLASE 5 - Op.Asig]: %s\n", yytext); }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 528 "scanner.l"
{ agregar_token(yytext, 5, 9); printf("[CLASE 5 - Op.Asig]: %s\n", yytext); }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 530 "scanner.l"
{
    agregar_token(yytext, 1, -1);
    printf("[CLASE 1 - Símb.Esp]: <<\n");
}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 534 "scanner.l"
{
    agregar_token(yytext, 1, -1);
    printf("[CLASE 1 - Símb.Esp]: >>\n");
}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 538 "scanner.l"
{
    agregar_token(yytext, 1, -1);
    printf("[CLASE 1 - Símb.Esp]: <\n");
}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 542 "scanner.l"
{
    agregar_token(yytext, 1, -1);
    printf("[CLASE 1 - Símb.Esp]: >\n");
}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 546 "scanner.l"
{
    agregar_token(yytext, 1, -1);
    printf("[CLASE 1 - Símb.Esp]: #!\n");
}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 550 "scanner.l"
{
    agregar_token(yytext, 1, -1);
    printf("[CLASE 1 - Símb.Esp]: #\n");
}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 554 "scanner.l"
{
    agregar_token(yytext, 1, -1);
    printf("[CLASE 1 - Símb.Esp]: *\n");
}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 558 "scanner.l"
{
    agregar_token(yytext, 1, -1);
    printf("[CLASE 1 - Símb.Esp]: |\n");
}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 562 "scanner.l"
{
    agregar_token(yytext, 1, -1);
    printf("[CLASE 1 - Símb.Esp]: °\n");
}
	YY_BREAK
case 22:
/* rule 22 can match eol */
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
YY_LINENO_REWIND_TO(yy_cp - 1);
(yy_c_buf_p) = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 567 "scanner.l"
{
agregar_token(yytext, 2, -1);
printf("[CLASE 2 - Identif]: %s\n", yytext);
}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 572 "scanner.l"
{
agregar_token(yytext, 3, -1);
printf("[CLASE 3 - Op.Aritm]: %s\n", yytext);
}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 577 "scanner.l"
{
agregar_token(yytext, 4, -1);
printf("[CLASE 4 - Op.Relac]: %s\n", yytext);
}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 584 "scanner.l"
{
agregar_token(yytext, 6, -1);
printf("[CLASE 6 - Cadena]: %s\n", yytext);
}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 590 "scanner.l"
{
    agregar_token(yytext, 8, -1);
    printf("[CLASE 8 - Real]: %s\n", yytext);
}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 594 "scanner.l"
{
    agregar_token(yytext, 8, -1);
    printf("[CLASE 8 - Real]: %s\n", yytext);
}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 598 "scanner.l"
{
    agregar_token(yytext, 8, -1);
    printf("[CLASE 8 - Real]: %s\n", yytext);
}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 603 "scanner.l"
{
agregar_token(yytext, 7, -1);
printf("[CLASE 7 - Entera]: %s\n", yytext);
}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 608 "scanner.l"
{
printf("[Comentario] %s\n", yytext);
}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 612 "scanner.l"
{
    fprintf(archivo_errores, "[ Error Léxico] '%s' en línea %d\n", yytext, yylineno);
    printf("[ Error Lexico]: %s\n", yytext);
}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 617 "scanner.l"
ECHO;
	YY_BREAK
#line 1626 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			yy_size_t num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				yy_size_t new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 146 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 146 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 145);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		yy_size_t number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			yy_size_t offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, yy_size_t  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	yy_size_t i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        yy_size_t yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
yy_size_t yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 617 "scanner.l"

/* === FIN DE LAS REGLAS LÉXICAS / INICIO DEL PARSER EMBEBIDO === */

/* Forward declarations for parser atomos variables */
extern char* atomos[];
extern int total_atomos;
extern int indice_actual;

void cargar_atomos(const char* archivo);
void Program();
void ListDecGlob();
void DecGlob();
void Decl();
void Tipo();
void list();
void Func();
void otraFunc();
void Arg();
void listArg();
void listaDec();
void listaSent();
void Sent();
void Asig();
void ExprGral();
void E();
void Ep();
void Tp();
void G();
void expRel();
void Sino();
void Param();
void listP();
void LlamaFunc();
void opRel();
void opAsig();
void OpAsigSimple();
void OpAsigComp();
void Fp();
void valRet();
// Prototipos de funciones agregadas
void HazM();


// === Helper para errores sintácticos ===
void errorSintactico(const char *esperado) {
    fprintf(archivo_errores, "[ Error Sintáctico] átomo '%s' (índice %d): se esperaba '%s'\n",
        (indice_actual < total_atomos ? atomos[indice_actual] : "EOF"),
        indice_actual,
        esperado);
}
/* === PUNTO DE ENTRADA: INVOCACIÓN DEL ANALIZADOR LÉXICO Y PARSER SINTÁCTICO === */
int main(int argc, char *argv[]) {
    if (argc != 2) {
        fprintf(stderr, "Uso: %s archivo_entrada\n", argv[0]);
        return 1;
    }

    FILE *entrada = fopen(argv[1], "r");
    if (!entrada) {
        perror("No se pudo abrir el archivo de entrada");
        return 1;
    }

    yyin = entrada;

    archivo_tokens = fopen("tokens.txt", "w");
    archivo_simbolos = fopen("simbolos.txt", "w");
    archivo_literales = fopen("literales.txt", "w");
    archivo_cadenas = fopen("cadenas.txt", "w");
    archivo_enteros = fopen("enteros.txt", "w");
    archivo_reales = fopen("reales.txt", "w");
    archivo_errores = fopen("errores.txt", "w");

    if (!archivo_tokens || !archivo_simbolos || !archivo_literales || !archivo_cadenas || !archivo_enteros || !archivo_reales || !archivo_errores) {
        fprintf(stderr, "No se pudieron abrir archivos de salida\n");
        return 1;
    }

    printf("Analizador Léxico iniciado...\n");
    printf("🪛 DEBUG: Iniciando análisis léxico...\n");
    printf("🪛 DEBUG: Ejecutando yylex()...\n");
    fclose(fopen("atomos.txt", "w"));  // Limpia atomos.txt
    yylex();
    printf("🪛 DEBUG: Finalizó yylex(). Tokens generados: %d\n", token_count);

    imprimir_tabla_tokens(archivo_tokens);
    imprimir_tabla_simbolos(archivo_simbolos);
    imprimir_tabla_literales(archivo_literales);
    imprimir_tabla_cadenas(archivo_cadenas);
    imprimir_tabla_enteros(archivo_enteros);
    imprimir_tabla_reales(archivo_reales);

    fclose(archivo_tokens);
    fclose(archivo_simbolos);
    fclose(archivo_literales);
    fclose(archivo_cadenas);
    fclose(archivo_enteros);
    fclose(archivo_reales);
    fclose(entrada);

    // Ahora, cargar los átomos y ejecutar el "parser" embebido:
    printf("Tablas escritas en archivos tokens.txt, simbolos.txt, literales.txt, cadenas.txt, enteros.txt y reales.txt\n");
    printf("Errores (léxicos y sintácticos) en 'errores.txt'\n");
    printf("🪛 DEBUG: Cargando átomos desde atomos.txt...\n");
    cargar_atomos("atomos.txt");
    printf("🪛 DEBUG: Iniciando análisis sintáctico con Program()\n");
    Program();
    printf("🪛 DEBUG: Terminó Program(). Atomos consumidos: %d de %d\n", indice_actual, total_atomos);
    if (indice_actual == total_atomos) {
        printf("✅ Análisis sintáctico exitoso. Todos los átomos fueron consumidos.\n");
    } else {
        printf("❌ Error: quedaron átomos sin procesar desde '%s'\n", atomos[indice_actual]);
    }

    fclose(archivo_errores);

    return 0;
}

// --- SINTÁCTICO: Variables y funciones para analizar los átomos generados ---
// (Colocados después de las reglas de Flex, en ámbito global)

char* atomos[MAX_TOKENS];
int total_atomos = 0;
int indice_actual = 0;

void cargar_atomos(const char* archivo) {
    FILE* f = fopen(archivo, "r");
    char linea[100];
    while (fgets(linea, sizeof(linea), f)) {
        linea[strcspn(linea, "\n")] = 0;
        atomos[total_atomos++] = strdup(linea);
    }
    fclose(f);
}

int match(const char* esperado) {
    printf("🪛 DEBUG: match(): esperando '%s', actual='%s' (índice %d)\n", esperado, atomos[indice_actual], indice_actual);
    if (indice_actual < total_atomos && strcmp(atomos[indice_actual], esperado) == 0) {
        printf("✔️ Match: %s\n", esperado);
        indice_actual++;
        return 1;
    } else {
        errorSintactico(esperado);
        printf("⚠️ Error sintáctico: se esperaba '%s' pero se encontró '%s'\n",
               esperado,
               (indice_actual < total_atomos ? atomos[indice_actual] : "EOF"));
        indice_actual++;
        return 0;
    }
}



// --- INICIO: Gramática para <Arg>, <listArg> y <listaDec> ---




// --- FIN: Gramática para <Arg>, <listArg> y <listaDec> ---







/* === PARSER: Decl === */




// --- INICIO: Gramática para listaSent y Sent ---












/* === PARSER: Program === */

// --- Fin sintáctico ---



// === STUBS DEL PARSER LL(1) ===
// Aquí se colocan las funciones para cada no-terminal de la gramática.
// Ejemplo de stubs previos:
// void Func() { ... }
// void otraFunc() { ... }
// void Arg() { ... }
// void listArg() { ... }

void listaDec() {
    if (indice_actual < total_atomos) {
        char *la = atomos[indice_actual];
        if (strcmp(la, "b") == 0 || strcmp(la, "c") == 0 ||
            strcmp(la, "n") == 0 || strcmp(la, "f") == 0) {
            Decl();
            listaDec();
        }
    }
}

void Func() {
    Tipo();
    match("a");
    match("(");
    Arg();
    match(")");
    match("[");
    listaDec();
    listaSent();
    match("]");
}

void otraFunc() {
    if (indice_actual < total_atomos && (
        strcmp(atomos[indice_actual], "b") == 0 ||
        strcmp(atomos[indice_actual], "c") == 0 ||
        strcmp(atomos[indice_actual], "n") == 0 ||
        strcmp(atomos[indice_actual], "f") == 0
    )) {
        Func();
        otraFunc();
    }
}

void Arg() {
    if (indice_actual < total_atomos &&
        (strcmp(atomos[indice_actual], "n") == 0 ||
         strcmp(atomos[indice_actual], "f") == 0 ||
         strcmp(atomos[indice_actual], "c") == 0 ||
         strcmp(atomos[indice_actual], "b") == 0)) {
        Tipo();
        match("a");
        listArg();
    }
}

void listArg() {
    if (indice_actual < total_atomos && strcmp(atomos[indice_actual], ",") == 0) {
        match(",");
        Arg();
    }
}

/* === PARSER FUNCTIONS FOR NON-TERMINALS (Parte I) === */

void Program() {
    // <Program> sólo inicia si el átomo actual es "g"
    printf("↪ Analizando &lt;Program&gt;, lookahead='%s' (índice %d)\n", atomos[indice_actual], indice_actual);
    if (indice_actual < total_atomos && strcmp(atomos[indice_actual], "g") == 0) {
        ListDecGlob();
        Func();
        otraFunc();
    } else {
        errorSintactico("Program (esperado: g)");
    }
}

void ListDecGlob() {
    // 2–3: <ListDecGlob> → <DecGlob> <ListDecGlob> | ε
    if (indice_actual >= total_atomos) {
        printf("🛑 DEBUG: Fin de entrada alcanzado en ListDecGlob (índice %d)\n", indice_actual);
        return;
    }

    printf("↪ Analizando <ListDecGlob>, lookahead='%s' (índice %d)\n", atomos[indice_actual], indice_actual);
    if (strcmp(atomos[indice_actual], "g") == 0) {
        DecGlob();
        ListDecGlob();
    } else {
        printf("ℹ️ DEBUG: <ListDecGlob> termina (no hay 'g') en índice %d\n", indice_actual);
    }
}

void DecGlob() {
    // 6: <DecGlob> → g <Decl>
    printf("↪ Analizando <DecGlob>, lookahead='%s'\n", atomos[indice_actual]);
    if (strcmp(atomos[indice_actual], "g") == 0) {
        match("g");
        Decl();
    } else {
        errorSintactico("g");
    }
}

void Decl() {
    // 7: <Decl> → <Tipo> a <list> ;
        printf("🧠 DEBUG: Entrando a Decl()\n");
    printf("↪ Analizando <Decl>, lookahead='%s'\n", atomos[indice_actual]);
    // FIRST(Decl) = b, c, n, f
    if (!(strcmp(atomos[indice_actual], "b") == 0 ||
          strcmp(atomos[indice_actual], "c") == 0 ||
          strcmp(atomos[indice_actual], "n") == 0 ||
          strcmp(atomos[indice_actual], "f") == 0)) {
        errorSintactico("Tipo esperado en Decl");
        return;
    }
    Tipo();
    match("a");
    list();
    match(";");
}

void Tipo() {
    // 8–11: <Tipo> → b | c | n | f
    printf("↪ Analizando <Tipo>, lookahead='%s'\n", atomos[indice_actual]);
     if (indice_actual >= total_atomos) {
        printf("🛑 DEBUG: Fin de entrada alcanzado en Tipo (índice %d)\n", indice_actual);
        return;
    }
    if (strcmp(atomos[indice_actual], "b") == 0) {
        match("b");
    } else if (strcmp(atomos[indice_actual], "c") == 0) {
        match("c");
    } else if (strcmp(atomos[indice_actual], "n") == 0) {
        match("n");
    } else if (strcmp(atomos[indice_actual], "f") == 0) {
        match("f");
    } else {
        errorSintactico("Tipo");
        indice_actual++;
    }
}

void list() {
    // 12–13: <list> → , a <list> | ε
    printf("↪ Analizando <list>, lookahead='%s'\n", atomos[indice_actual]);
    printf("🪛 DEBUG: Entering <list>\n");
    if (indice_actual < total_atomos && strcmp(atomos[indice_actual], ",") == 0) {
        printf("🪛 DEBUG: <list> comma branch taken\n");
        match(",");
        match("a");
        list();
    } else {
        printf("🪛 DEBUG: <list> epsilon branch taken (no comma)\n");
    }
}

/* — Próximas funciones a implementar:
   Func, otraFunc, Arg, listArg, listaDec, Sent, Asig, opAsig,
   ExprGral, E, T, F, etc.
*/

/* === NUEVO PARSER RECURSIVO DESCENDENTE CON getchar() === */
char c;

// Manejadores de aceptación y rechazo
void aceptar() {
    printf("✅ Cadena aceptada\n");
    exit(0);
}
void rechazar() {
    printf("❌ Error sintáctico en caracter '%c'\n", c);
    exit(1);
}

// Avanza al siguiente caracter
void avanzar() {
    c = getchar();
}

// Declaración de las funciones para cada no-terminal de tu gramática


void DecGlob();
void Decl();
void Para();
void list();
void Func();
void otraFunc();
void Arg();
void listArg();
void listaDec();
void listaSent();
void Sent();
void Asig();
void Si(void);
void Dev(void);
void ExprGral();
void E();
void T();
void Expr();
void Cuerpo();
void F();
void listaSent() {
    if (indice_actual < total_atomos) {
        const char *la = atomos[indice_actual];
        // todos los posibles primeros de Sent
        if (strcmp(la, "a") == 0 || strcmp(la, "h") == 0 || strcmp(la, "i") == 0 ||
            strcmp(la, "o") == 0 || strcmp(la, "d") == 0 || strcmp(la, "t") == 0 ||
            strcmp(la, "p") == 0 || strcmp(la, "m") == 0) {
            Sent();
            listaSent();
        }
        // else ε (no hacer nada)
    }
}



void Sent() {
    if (indice_actual < total_atomos) {
        char *la = atomos[indice_actual];

        if (strcmp(la, "a") == 0) {
            Asig();
            match(";");
        } else if (strcmp(la, "h") == 0) {
            // h [ <listaSent> ] w ( <expRel> ) [ <listaSent> ]
            match("h");
            match("[");
            listaSent();
            match("]");
            match("w");
            match("(");
            expRel();
            match(")");
            match("[");
            listaSent();
            match("]");
        } else if (strcmp(la, "i") == 0) {
            // i ( <expRel> ) [ <listaSent> ] <Sino>
            Si();
        } else if (strcmp(la, "o") == 0) {
            // o ( <ExprGral> ) [ <listaSent> ]
            Para();
        } else if (strcmp(la, "d") == 0) {
            // d <valRet> ;
            Dev();
        } else if (strcmp(la, "t") == 0) {
            match("t");
            match(";");
        } else if (strcmp(la, "p") == 0) {
            match("p");
            match(";");
        } else if (strcmp(la, "m") == 0) {
            match("m");
            match(";");
        } else {
            errorSintactico("Sent");
            indice_actual++; // skip erroneous token to avoid infinite loop
        }
    }
}

void Asig() {
    if (indice_actual < total_atomos && strcmp(atomos[indice_actual], "a") == 0) {
        match("a");
        opAsig();
        ExprGral();
    } else {
        errorSintactico("a");
        indice_actual++;
    }
}





void opAsig() {
    if (indice_actual < total_atomos) {
        char *la = atomos[indice_actual];
        if (strcmp(la, "=") == 0) {
            OpAsigSimple();
        } else if (
            strcmp(la, "#") == 0 || strcmp(la, "ñ") == 0 || strcmp(la, "$") == 0 ||
            strcmp(la, "v") == 0 || strcmp(la, "?") == 0 || strcmp(la, ":") == 0 ||
            strcmp(la, "\"") == 0 || strcmp(la, "^") == 0 || strcmp(la, "&") == 0
        ) {
            OpAsigComp();
        } else {
            errorSintactico("opAsig");
            indice_actual++;
        }
    }
}

void ExprGral() {
    // FIRST(ExprGral) = { "a", "e", "r", "s", "(" }
    char *la = atomos[indice_actual];
    if (strcmp(la, "a") == 0 || strcmp(la, "e") == 0 ||
        strcmp(la, "r") == 0 || strcmp(la, "s") == 0 ||
        strcmp(la, "(") == 0) {
        E();
    } else {
        errorSintactico("ExprGral");
        indice_actual++;
    }
}
void T() {
    // FIRST(T) = { "a", "e", "r", "s", "(" }
    char *la = atomos[indice_actual];
    if (strcmp(la, "a") == 0 || strcmp(la, "e") == 0 ||
        strcmp(la, "r") == 0 || strcmp(la, "s") == 0 ||
        strcmp(la, "(") == 0) {
        F();
        Tp();
    } else {
        errorSintactico("T");
        indice_actual++;
    }
}

void Tp() {
    if (indice_actual < total_atomos &&
        (strcmp(atomos[indice_actual], "*") == 0 ||
         strcmp(atomos[indice_actual], "/") == 0 ||
         strcmp(atomos[indice_actual], "%") == 0 ||
         strcmp(atomos[indice_actual], "~") == 0 || // dive
         strcmp(atomos[indice_actual], "k") == 0)) { // exp
        match(atomos[indice_actual]);
        F();
        Tp();
    }
}





void E() {
    // FIRST(E) = { "a", "e", "r", "s", "(" }
    char *la = atomos[indice_actual];
    if (strcmp(la, "a") == 0 || strcmp(la, "e") == 0 ||
        strcmp(la, "r") == 0 || strcmp(la, "s") == 0 ||
        strcmp(la, "(") == 0) {
        T();
        Ep();
    } else {
        errorSintactico("E");
        indice_actual++;
    }
}

void F() {
    // <F> → a F' | e | r | s | ( E ) | { LlamaFunc } | m
    if (indice_actual < total_atomos) {
        const char *la = atomos[indice_actual];
        if (strcmp(la, "a")==0 || strcmp(la, "e")==0 ||
            strcmp(la, "r")==0 || strcmp(la, "s")==0) {
            match(la);
            Fp();      // maneja j o z (postfijo)
        }
        else if (strcmp(la, "(")==0) {
            match("("); E(); match(")");
        }
        else if (strcmp(la, "{")==0) {
            LlamaFunc();
        }
        else if (strcmp(la, "m")==0) {
            match("m");
        }
        else {
            errorSintactico("F");
            indice_actual++;
        }
    }
}



void opRel() {
    if (indice_actual < total_atomos) {
        char *la = atomos[indice_actual];
        if (
            strcmp(la, "h") == 0 || strcmp(la, "m") == 0 ||
            strcmp(la, "¡") == 0 || strcmp(la, "!") == 0 ||
            strcmp(la, "x") == 0 || strcmp(la, "y") == 0
        ) {
            match(la);
        } else {
            errorSintactico("opRel");
            indice_actual++;
        }
    }
}

void G() {
    if (indice_actual < total_atomos) {
        const char *la = atomos[indice_actual];
        if (strcmp(la, "z") == 0) {
            match("z");
        } else if (strcmp(la, "j") == 0) {
            match("j");
        }
        // else: ε (no hacer nada)
    }
}

void Fp() {
    if (indice_actual < total_atomos) {
        if (strcmp(atomos[indice_actual], "j") == 0 || strcmp(atomos[indice_actual], "z") == 0) {
            match(atomos[indice_actual]); // j o z
        }
        // Si no es j o z, entonces es ε (no hacer nada)
    }
}

void expRel() {
    // FIRST(expRel) = FIRST(ExprGral) = { a, e, r, s, ( }
    const char *la = atomos[indice_actual];
    if (strcmp(la, "a") == 0 || strcmp(la, "e") == 0 ||
        strcmp(la, "r") == 0 || strcmp(la, "s") == 0 || strcmp(la, "(") == 0) {
        ExprGral();
        opRel();
        ExprGral();
    } else {
        errorSintactico("expRel");
        indice_actual++;
    }
}

void OpAsigComp() {
    if (indice_actual < total_atomos) {
        char *la = atomos[indice_actual];
        if (
            strcmp(la, "#") == 0 || strcmp(la, "ñ") == 0 ||
            strcmp(la, "$") == 0 || strcmp(la, "v") == 0 ||
            strcmp(la, "?") == 0 || strcmp(la, ":") == 0 ||
            strcmp(la, "\"") == 0 || strcmp(la, "^") == 0 ||
            strcmp(la, "&") == 0
        ) {
            match(la);
        } else {
            errorSintactico("OpAsigComp");
        }
    }
}

void OpAsigSimple() {
    if (indice_actual < total_atomos && strcmp(atomos[indice_actual], "=") == 0) {
        match("=");
    } else {
        errorSintactico("OpAsigSimple");
    }
}



void Param() {
    if (indice_actual < total_atomos && strcmp(atomos[indice_actual], ",") == 0) {
        match(",");
        ExprGral();
        Param();
    }
}


void listP() {
    if (indice_actual < total_atomos) {
        const char *la = atomos[indice_actual];
        // first(ExprGral) = {"s","q","m","u","(","a","n","r"}
        if (strcmp(la, "s") == 0 || strcmp(la, "q") == 0 ||
            strcmp(la, "m") == 0 || strcmp(la, "u") == 0 ||
            strcmp(la, "(") == 0 || strcmp(la, "a") == 0 ||
            strcmp(la, "n") == 0 || strcmp(la, "r") == 0) {
            ExprGral();
            Param();
        }
    }
}



void Args() {
    if (indice_actual < total_atomos) {
        const char *la = atomos[indice_actual];
        // FIRST(ExprGral) = { a, e, r, s, ( }
        if (strcmp(la, "a") == 0 || strcmp(la, "e") == 0 ||
            strcmp(la, "r") == 0 || strcmp(la, "s") == 0 ||
            strcmp(la, "(") == 0) {
            ExprGral();
            Param();
        }
        // else: ε
    }
}




// Definition for yywrap to allow Flex lexer to link
int yywrap(void) {
    return 1;
}

void Ep() {
    if (indice_actual < total_atomos &&
        (strcmp(atomos[indice_actual], "+") == 0 ||
         strcmp(atomos[indice_actual], "-") == 0)) {
        match(atomos[indice_actual]);
        T();
        Ep();
    }
}
void Cuerpo() {
    if (indice_actual < total_atomos && strcmp(atomos[indice_actual], "[") == 0) {
        match("[");
        listaSent();
        match("]");
    } else {
        errorSintactico("Cuerpo (esperado: [)");
        indice_actual++;
    }
}
void Expr() {
    if (indice_actual < total_atomos) {
        const char *la = atomos[indice_actual];
        // FIRST(E) = { a, e, r, s, ( }
        if (strcmp(la, "a") == 0 || strcmp(la, "e") == 0 ||
            strcmp(la, "r") == 0 || strcmp(la, "s") == 0 ||
            strcmp(la, "(") == 0) {
            E();
        } else {
            errorSintactico("Expr (esperado: a, e, r, s, ()");
            indice_actual++;
        }
    }
}






void Sino() {
    if (indice_actual < total_atomos && strcmp(atomos[indice_actual], "l") == 0) {
        match("l");
        match("[");
        listaSent();
        match("]");
    }
}
void Dev() {
    if (indice_actual < total_atomos && strcmp(atomos[indice_actual], "d") == 0) {
        match("d");
        valRet();
        match(";");
    } else {
        errorSintactico("Dev (esperado: d)");
        indice_actual++;
    }
}

void valRet() {
    const char *la = atomos[indice_actual];
    if (strcmp(la, "a") == 0 || strcmp(la, "e") == 0 ||
        strcmp(la, "r") == 0 || strcmp(la, "s") == 0 ||
        strcmp(la, "(") == 0) {
        ExprGral();
    } else {
        errorSintactico("valRet (esperado: a, e, r, s, ()");
        indice_actual++;
    }
}
void Si() {
    if (indice_actual < total_atomos && strcmp(atomos[indice_actual], "i") == 0) {
        match("i");
        match("(");
        expRel();
        match(")");
        match("[");
        listaSent();
        match("]");
        Sino();
    } else {
        errorSintactico("Si (esperado: i)");
        indice_actual++;
    }
}

void Para() {
    if (indice_actual < total_atomos && strcmp(atomos[indice_actual], "o") == 0) {
        match("o");
        match("(");
        E(); // o(E)
        match(")");
        match("[");
            listaSent();
        match("]");
    } else {
        errorSintactico("Para (esperado: o)");
        indice_actual++;
    }
}

void LlamaFunc() {
    match("{");
    match("a");
    match("(");
    listP();
    match(")");
    match("}");
}


void HazM() {
    if (indice_actual < total_atomos && strcmp(atomos[indice_actual], "h") == 0) {
        match("h");
        match("[");
        listaSent();
        match("]");
    } else {
        errorSintactico("HazM (esperado: h)");
        indice_actual++;
    }
}



